tarides/opam-monorepo

- src/opam_cmd.ml
Github download URLs are normally of the form:
https://github.com/proj/repo/archive/tag.extension
but it also supports URLs of the form:
https://github.com/proj/repo/archive/tag/filname.extension
which allows better control of the final filename. This patch
adds support for the latter.
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
> Support github URLs with non-standard filenames

- src/dune_cmd.ml
- src/opam_cmd.ml
- src/types.ml
Just moving an internal project to duniverse and needed these changes for support. This supports adding a opam repo to the duniverse switch and then pulling git+ssh packages from it when it's on a private git server.
> git+ssh support

- README.md
- doc/spec.md
- src/config.ml
- src/duniverse.ml
The name `ocaml_modules` might be slightly confusing as we're not actually vendoring ocaml modules but entire dune projects.
> Move vendored sources from ocaml_modules to duniverse

- src/config.ml
- src/dune_cmd.ml
- src/exec.ml
- src/opam_cmd.ml
- src/types.ml
Use an opam repository to resolve dune overlay packages, instead of hardcoding the list in the source code.
The repo is here: https://github.com/dune-universe/opam-overlays
The repository is added to the local switch with the name `dune-overlays`, adding potential name collision.
This adds a regression: If there is no dune overlay for the lastest version of a package, the upstream version will be selected.
It can be fixed by checking if a dunified older version exists in the "package does not depend on dune" branch.
> Use an opam repo to resolve dune overlays

- .docker.sh
- .travis.yml
This is just a quick-fix, I'm not sure what the future of `duniverse` CI should be.
I first thought about using the regular `.travis-docker.sh`, which would work but I seem to recall a mention of `duniverse` being a standalone tool with vendored dependencies, in which case updating the custom CI script seems better!
> Fix CI script

- lib/exec.ml
- lib/exec.mli
- lib/opam_cmd.ml
- lib/types.ml
This PR remove the local switch from `.duniverse` and uses a completely new `.opam` for each `duniverse opam` run instead to make this step stateless.
It comes at a price since subsequent run of `duniverse opam` won't benefit from the switch creation.
I rebased this on top of #10  (and thus set it to draft) to get the working CI. Only the last commit is relevant to this PR!
> Use a new and temporary opam state for each duniverse-opam run

- lib/exec.ml
- lib/exec.mli
Depends on #6 
In an effort to clean up the `duniverse` repo I started adding `.mli` files for the duniverse internal library. `Exec` is the first in that series but I'm planning on doing so for the remaining modules.
I exposed the functions that were used outside the module and added a bit of documentation.
I took the liberty of getting rid of the unused values. Some of them were commented as so so I'm guessing that we're planning on using them at some point in the future. I removed them but I'm happy ot open an issue to document that soon to be feature if you feel like it's useful!
> Add an .mli to the Exec module

- README.md
- bin/duniverse.ml
We accidentally modified the README which is generated from the `Cmdliner` documentation of the `duniverse` binary and thus every time we build the project, this change was overwritten.
Might be worth moving this to a different file and having a proper README for the repo but that's a different story. I'll work on that as well!
> Fix a few quirks in the documentation and the generated README

- bin/duniverse.ml
- lib/exec.ml
- lib/exec.mli
- lib/git_cmd.ml
- lib/opam_cmd.ml
- lib/types.ml
As a followup to #8 and #9 `duniverse opam` now uses an temporary opam state with an empty switch.
This makes it much faster as we don't have to compile ocaml anymore.
The output of `opam list --resolve` will now give us a bunch of new dependencies such as `ocaml-base-compiler` and `base-bigarray` but they are properly handled by `classify_package`. This was a bit cryptic and hard to figure out so we should probably improve that part of the code in the future but it works for now.
As a side effect, the `Opam_cmd.init_duniverse` function doesn't need the `compiler` argument anymore so I removed it, both from the command line arguments and from the `Types.Opam.t` type. Be aware that this is a breaking change to `duniverse opam` and `duniverse lock`.
Another point worth noting is that now, …
> Use a temporary empty switch for dependencies resolution

- .docker.sh
- Makefile
- dune-project
- examples/basic/basic.ml
- examples/basic/basic.opam
- examples/basic/dune
- examples/basic/dune-project
- examples/build-examples.sh
- examples/dune
Depends on #12 on top of which it is rebased. This is required to have a fast enough CI as compiling ocaml in a docker was terribly slow.
Only the last commit is relevant to this PR, please don't merge before #12 !
This PR adds a simple integration test. We build a simple binary which depends both on a regular upstream packages and a dune-overlay one using `duniverse` and make sure everything work fine.
As I was working on this I figured we could probably improve our CI to make better use of the docker's cache but this can be done separately!
> Add integration tests

- lib/exec.ml
- lib/exec.mli
- lib/opam_cmd.ml
- lib/opam_show_result.ml
- lib/opam_show_result.mli
- lib/types.ml
- test/test_duniverse_lib.ml
- test/test_opam_show_result.ml
- test/test_opam_show_result.mli
Instead of calling opam three times per package dependency, fetch and parse everything at once.
This is _a lot_ faster.
> Faster duniverse opam fetch using one single command.

- README.md
- bin/duniverse.ml
- lib/exec.ml
- lib/exec.mli
- lib/opam_cmd.ml
A first and straightforward solution to https://github.com/avsm/duniverse/issues/19.
It keeps tracks of non-dune packages and allow to install them using `duniverse opam-install`.
> duniverse opam-install command

- lib/opam_cmd.ml
- test/test_opam_cmd.ml
This PR add a couple test and minor robustness improvements to the parsing of archive URLs.
It used to crash on empty archive fields and although this should not happen, better be safe than sorry.
> Improve tag_from_archive

- test/test_opam_cmd.ml
- test/test_opam_show_result.ml
This makes it easier to follow the error reports when a lot of tests failed.
> Pass test name to Alcotest.check

- lib/dune_cmd.ml
- lib/opam_cmd.ml
- lib/types.ml
- test/test_opam_cmd.ml
Depends on #33, please do not merge before!
As promised I removed the github variant as we were not taking any advantage from it. I believe the code could probably be simplified further as I don't think the `"dev-repo without a host"` error case is necessary but let's keep things simple here. This is just another step towards the duniverse content representation!
Opening as draft until #33 is merged, I'll assign reviewers once it's done!
> Remove GitHub variant from dev_repo

- .dockerfiles/opam
- cli/init.ml
- cli/styled_pp.ml
- cli/styled_pp.mli
- lib/dune_cmd.ml
- lib/duniverse.ml
- lib/duniverse.mli
- lib/exec.ml
- lib/exec.mli
- lib/opam.ml
- lib/opam_cmd.ml
- lib/pp_combinators.ml
- lib/pp_combinators.mli
- lib/types.ml
- test/test_duniverse.ml
- test/test_duniverse.mli
- test/test_duniverse_lib.ml
- test/test_opam_show_result.ml
- test/test_opam_show_result.mli
Depends on #38 so creating as draft.
This PR aims at using a better internal representation of the `duniverse` so that the "hard" part is building and there's no need for complex logic when manipulating it afterwards.
In other word once `duniverse init` has written the `dune-get`, rest is easy.
It's a pretty big PR compared to what we had so far so I'll try to summarize the changes here a bit. This is a refactoring and shouldn't result in a change of behaviour of the tool (with one exception that I'll bring up later).
The duniverse is now split in two parts: the configuration and the dependencies.
The configuration is just the set of parameters we use to resolve the dependencies during the `init` command and that we might eventually reuse elsewhere, especially if we need to run opam …
> Improve duniverse representation

- lib/opam.ml
- test/test_opam.ml
Previously URIs such as `git://github.com/lpw25/async_graphics` weren't recognized as git URIs, leading to such dependencies to be skipped by duniverse.
This PR adds support for such URIs.
> Improve dev repo parsing

- lib/opam_cmd.ml
- test/test_opam_cmd.ml
In an attempt to solve https://github.com/avsm/duniverse/issues/37
Basically it tries to parse url.src as a dev-repo field before having to fallback on the actual dev-repo field.
> Rely less on dev-repo field (e.g. for opam pins)

- cli/pull.ml
- lib/exec.ml
- lib/git.ml
- lib/git.mli
- test/test_git.ml
This fixes an issue with a log about the registered commit not being the head commit for the ref anymore. It used to appear when the repo had packed-refs.
The bug is fixed and that log is now info level since there are valid use case for sticking to an older commit.
> Fix git ref resolution with packed-refs

- cli/common.ml
- cli/pull.ml
- lib/dune
- lib/duniverse.ml
- lib/parallel.ml
- lib/parallel.mli
- test/test_duniverse_lib.ml
- test/test_parallel.ml
- test/test_parallel.mli
`duniverse init` and `duniverse pull` spend a great amount of time waiting for the network. Using threads allows a nice amount of parallelization, thus improving overall speed.
Some benchmarks for 105 packages.
`duniverse init`: 
* 1 thread: ∞ (> 1m)
* 20 threads: 30s
* 100 threads: 28s
`duniverse pull`:
* 1 thread: ∞ (> 1m)
* 24 threads: 10s
> Use threads to speed up init and pull

- lib/git.ml
- test/test_git.ml
The error message when `git ls-remote` returns nothing was not very helpful as pointed out in #56.
This PR adds a preliminary check for the empty output to return an appropriate error.
The message is now:
```
duniverse: No 3.5.0 ref for git://github.com/facebook/reason.git
```
instead of:
```
duniverse: Invalid git ls-remote output line: ""
```
> Improve error reporting when resolving git refs

- cli/init.ml
- lib/exec.ml
- lib/exec.mli
A few users have been reporting issues when working with duniverse when the opam file contains uncommitted changes. This I believe it is due to the fact that opam infers the pinning method based on the content of the directory and picks `"git"`. Now we explicitly pass `path` when pinning the local packages so that `duniverse init` reflects the current state of the opam file which makes it much more convenient to work with.
> Path pin local packages when initializing duniverse

- lib/exec.ml
- lib/git.ml
- lib/git.mli
- test/test_git.ml
See https://github.com/dune-universe/opam-overlays/pull/49#issuecomment-522923531
- Only search for `refs/heads/<ref>` (branches) and `refs/tags/<ref>` (tags) in the output of `git ls-remote`.
Remotes may have more refs but they should/can not be used, we only want branch/tags.
There should never be two refs with the same full name (`refs/...`).
- Fix a bug with the `is_suffix` logic
"abc" could match "refs/heads/xabc"
- ~~Remove the `Multiple_such_ref` error and choose tags first~~
~~If a tag and a branch have the same name, the tag is chosen. To avoid failing.~~
> Improve parsing of git ls-remote

- cli/common.ml
- cli/common.mli
- cli/init.ml
- cli/opam_install.ml
- cli/pull.ml
- cli/update.ml
Cmdliner Args are now wrapped with a constructor to avoid confusion in the `run` function arguments.
@craigfe set that up for `mdx` and I thought it would be a good idea to do the same here!
> Improve use of cmdliner Args

- .ocamlformat
I believe this is best practice although the error message isn't necessarily great it's still better than reformatting everything by mistake if you run the wrong version of ocamlformat.
It will also be helpful to benefit from https://github.com/ocaml-ci/ocaml-ci/pull/49
> Add explicit version to .ocamlformat

- cli/init.ml
- cli/pull.ml
- lib/duniverse.ml
- lib/duniverse.mli
- lib/exec.ml
- lib/exec.mli
`duniverse pull` will now clone the source code and add each of
the vendored packages as a git submodule. It does this by adding
the submodule commit objects after the source pulls have been done.
This is a lot faster than the default `git submodule add` which
requires setting up remote tracking branches for each of the
remotes.
This adds a `--no-submodules` option to `pull` to just do a
source code clone.
> Pull source as git submodules by default

- .ocamlformat
- cli/init.ml
- cli/pull.ml
- lib/dune
- lib/duniverse.ml
- lib/duniverse.mli
- lib/exec.ml
- lib/exec.mli
The first commit is reformatting using 0.12 (was not formatted, [ocaml-ci](https://ci.ocamllabs.io/github/ocamllabs/duniverse/commit/08500e3b/variant/lint)).
The upgrade creates no diff.
> Upgrade ocamlformat

- README.md
- bin/duniverse.ml
- cli/common.ml
- cli/common.mli
- cli/init.ml
- cli/pin.ml
- cli/pull.ml
- lib/config.ml
- lib/duniverse.ml
- lib/duniverse.mli
- lib/opam_cmd.ml
- lib/opam_solve.ml
- lib/pins.ml
- lib/pull.ml
- lib/pull.mli
This PR adds support for pinned packages to duniverse.
Pinned packages can be added to the `dune-get` file with `duniverse pin PACKAGE REPO`. When a pin is found in `dune-get` during `duniverse init` it will be pulled and included in the dependency resolution. An opam entry with a fixed ref is attributed to each pin and saved in `dune-get` to achieve reproducible pulls and builds.
In addition to including the pins in the dependency resolution, the opam files of the pinned packages are stored in `Config.pins_dir`. These files can be optionally changed to override build options or dependencies, for example.
The pinned packages are included in the `config` section of the duniverse. Here's an example:
```lisp
((config
((version 1) (root_packages (((name my-app))))
(pins
(((pin …
```
> Add pin management to duniverse

- cli/pin.ml
Forces init on every pin change. This results in repeated dep recomputations when adding multiple pins, but saves time for the the most common case – "I just want to pin this".
This addresses the second point in https://github.com/ocamllabs/duniverse/pull/87#issuecomment-640549805.
> Update dependencies (i.e. run init) when adding/removing pins.

- lib/pins.ml
Minor changes to version used in package directories in `./duniverse`.
I'm not sure if `zdev` is intentional or if it was just a typo. Happy to revert.
> Pin versions

- cli/pin.ml
Currently duniverse will terminate with an error when adding a pin that already exists in the config file. This PR changes this behaviour to ask the user for confirmation to replace the existing pin.
Resolves the first point in https://github.com/ocamllabs/duniverse/pull/87#issuecomment-640549805
I also renamed `to_add` and `to_remove` to `pin_name`, seemed a bit better.
> Confirm if an existing pin should be replaced.

- README.md
- cli/lock.ml
- lib/config.ml
@TheLortex recently noticed this suggestion was not up to date. The new plugin doesn't require a single repo with dune packages only and it therefore makes more sense to suggest adding the overlays to the current switch configuration.
> Update the suggested repo to add

- CHANGES.md
- cli/lock.ml
- lib/repo.ml
- lib/repo.mli
My proposal to fix https://github.com/ocamllabs/opam-monorepo/issues/150
Each commit is more or less independent from the other, so we can discuss them separately if needed. 
The first one is a bug fix, as it was already intended to ignore `_build` and `duniverse` folders.
The second one is the addition of an error message.
The third one allows the user to use `opam monorepo lock` even if conflicting package definitions exist, as long as the requested package name is given.
> Fix opam recursion when performing the lock step

- CHANGES.md
- lib/exec.ml
- lib/git.ml
- lib/git.mli
- test/test_git.ml
As suggested by @emillon, we can use `git ls-remote --symref` to find the main branch of a given remote. The output is language-agnostic so that fixes #114. It also allows `opam-monorepo` to work outside of git repositories.
I added tests so hopefully I won't break anything.
> Use a more robust way of finding the main branch

- CHANGES.md
- cli/lock.ml
- lib/opam.ml
- lib/opam.mli
- lib/opam_solve.ml
- lib/opam_solve.mli
Since dune 2.0, `jbuild` files are not supported. As a consequence, if `opam monorepo` was to vendor a project depending on `jbuilder`, it would break the whole monorepo build.   
There are two changes in this PR:
- by default: don't include packages depending on `jbuilder` for the lockfile resolution.
- add a `--allow-jbuilder` option to enable the old behavior.
> Exclude packages depending on jbuilder by default

- CHANGES.md
- cli/lock.ml
- lib/opam_solve.ml
- lib/opam_solve.mli
The new argument `--ocaml-version` allows to determine the ocaml version in the lockfile that's being generated. In particular, it allows to work around [this current issue](https://github.com/ocaml-opam/opam-0install-solver/issues/25) in Oinstall when using opam-monorepo.
> Add argument `--ocaml-version` to `lock`

- CHANGES.md
- cli/lock.ml
When given an opam git remote in the form `git+https://github.com/...`, `git ls-remote --symref <remote> HEAD` would fail as it doesn't recognize urls in the form `git+https`, because this is something specific to opam. 
This PR applies the same mechanism as in `resolve_ref`, which is to remove the `git+` prefix in that situation.
> Fix git default branch computation

- .github/workflows/test.yml
The github actions were slightly broken. This is an attempt to fix them until we can fully rely on `ocaml-ci`.
@avsm unless you're okay with deleting the Binaries actions, could you look into why they are broken?
> Update Github actions

- CHANGES.md
- lib/opam_solve.ml
Some packages such as `opam-file-format` are compatible with dune but don't use it as their primary build mechanism. They mark dune as an optional dependency which made opam-monorepo think they weren't building with dune when they actually could be built with it and therefore could be vendored in a duniverse.
This PR fixes that.
> Improve detection of packages building with dune

- CHANGES.md
- cli/lock.ml
- lib/opam_solve.ml
Fixes #171 
The full list is now only printed when the verbosity level is strictly higher than 0 (the default). The number of root packages is printed instead.
This also removes a couple places where the full list was printed again.
> Quieter lock logs

- CHANGES.md
- lib/opam.ml
- lib/opam.mli
- lib/opam_solve.ml
- test/test_opam.ml
This was causing the solver to select unreleased ocaml versions sometimes because their dependency could be met using packages such as `ocaml-variants.4.11.3+trunk`.
The variant selected this way made no particular sense as well since the solver was picking the highest version number according to the `+<variant-feature>` suffixes.
The solution is now required to include an `ocaml-base-compiler` unless one the local packages explicitly depends on an `ocaml-variants` package or one of the `ocaml-option-*` packages.
> Discard ocaml variants by default

- CHANGES.md
- cli/lock.ml
If no `~rt` argument is passed to `OpamSwitchState.with_`, it will load the repository state itself. We already load this state in `check_repo_config`, so this was causing it to be loaded twice.
Instead, we can load it manually and pass it as argument and it will use it.
Since that function dominates lock time, this makes lock twice as fast (on opam-monorepo itself: 12.4s down to 6.7s).
> Make lock 2x faster by loading repo state once

- CHANGES.md
- cli/pull.ml
- dune-project
- lib/dune
- lib/dune_file.ml
- lib/dune_file.mli
- opam-monorepo.opam
- test/test_dune_file.ml
This used to crash under some circumstances on windows machines because it wouldn't handle CRLF properly.
The new code uses regexp to properly extract the version without being sensitive to leftover CR and replace just the version number, without modifying the rest of the file, including of course, CRLF.
I also updated the code that appends a lang stanza even though it's unlikely we'll need it again for a very long time. It now tries to
respect the newline convention found inside the file, defaulting to good old `\n` if it can't figure it out.
Finally, I added a bunch of unit tests for this in the process.
> Fix dune-project handling under windows

- CHANGES.md
- cli/lock.ml
This simplifies a bit how states are loaded:
- repo state is automatically loaded when switch state is loaded
- repo state can be accessed as a field of switch state
> Access repo state through switch state

- CHANGES.md
- cli/common.ml
- cli/common.mli
- cli/lock.ml
- cli/pull.ml
- cli/pull.mli
- lib/config.ml
- lib/repo.ml
- lib/repo.mli
Fixes #162 
The lockfile path inference mechanism was broken because it depended on which packages were locked on one hand (when running `lock`) and only on which packages were defined at the root of the project on the other (when running `pull`).
It is now symetrical and only relies on the project name as defined in the `dune-project` file so `lock` and `pull` will get to the same conclusion regarding its location. This can be considered a breaking change as single package repositories could get away without defining a name in the dune-project before and can't do that anymore. I think it is fine to ask of our users that they fill in this field.
I also added a CLI option to explicitly set the path to the lockfile, providing a bit of flexibility for specific use cases.
> Fix lockfile path inference

- CHANGES.md
- cli/lock.ml
- lib/opam.ml
- lib/opam.mli
- lib/opam_solve.ml
- lib/opam_solve.mli
- lib/pin_depends.ml
- lib/pin_depends.mli
- test/test_duniverse_lib.ml
- test/test_pin_depends.ml
- test/test_pin_depends.mli
This is a rebase of @rizo's PR: https://github.com/ocamllabs/opam-monorepo/pull/159
Fixes https://github.com/ocamllabs/opam-monorepo/issues/153
> Pin depends

- CHANGES.md
- lib/git.ml
- test/test_git.ml
Fixes https://github.com/ocamllabs/opam-monorepo/issues/127
In the ref resolution we can check if a commit exists when it's pointed by an existing ref. 
Otherwise we just check if it looks like a commit (hex numbers), assume it exists in the remote and emit a warning.
> Commit_pointed_by: partial support when ref is a commit

- CHANGES.md
- bin/opam_monorepo.ml
- cli/dune
- lib/dune
If not set then OPAM does not set the right path for the OPAM root and will use the default `~/.opam` no matter what. The OPAM API is surprising in this regard that even passing the root folder to `load_defaults` does not actually end up setting the folder.
Closes #197
> Set the `root_dir` in the OPAM state

- .ocamlformat
- CHANGES.md
- cli/dune
- lib/dune
- opam-monorepo.opam.locked
This upgrades our lockfile to the latest versions of our deps, in particular it upgrades the opam libs to actual 2.1 instead of the `rc2` versions.
> Upgrade lockfile and ocamlformat

- cli/dune
- lib/dune
We don't use Lwt seemingly anywhere.
Closes #196.
> Remove Lwt dependency

- cli/common.ml
- cli/lock.ml
- cli/pull.ml
- lib/project.ml
- lib/project.mli
As a follow up to #218 I renamed the `Repo` module to `Project` which is more accurate of a name.
Also replaced a hand assembled dune-project path with a call to the proper function from the above mentioned module.
> Rename Repo to Project

- opam-monorepo.opam
- opam-monorepo.opam.template
As observed by @emillon `opam pin add opam-monorepo --dev` is failing because we're missing the pin in the original `opam` file. This adds it.
Tested on a fresh OPAM switch, it builds fine now.
> Add our fork of opam-0install-solver as a pin-depend

- CONTRIBUTING.md
It might be tempting to use opam-monorepo on itself but the latest released version should be used instead, to make sure
the CI can keep functioning at all time and that new, potentially untested features don't break our dev workflow.
> Clarify which opam-monorepo to use in opam-monorepo

- lib/opam_solve.ml
The solver was running properly, with the pins enabled but the packages appearing in a pin-depends field of one of the local packages were filtered out of the final solution.
> Fix a recent bug where pin-depends would be excluded form the lockfile

- CHANGES.md
- cli/lock.ml
- lib/opam_solve.ml
- lib/opam_solve.mli
By default 0install-solver will display `...` after the first 5 candidates. Now when `--verbose` is passed it displays everything.
> Display the full solver error with --verbose

- lib/lockfile.ml
The bug was discovered by @samoht in #217. When rebuilding a `Duniverse.t` from a `Lockfile.t`, some packages in the `provided_packages` list would be duplicated, one for every repo in the duniverse.
This was due to a misinterpretation of the `OpamStd.Map.update` arguments semantic.
I did not add a changelog entry as this bug was not observable from the outside, the provided packages are not used by pull so it had no impact until we started working on the `list` subcommand.
A good follow up to this might be to clean up our internal representation to use a `Set` there since we want to express the uniqueness.
> Fix a bug in `Lockfile.to_duniverse` that duplicated provided_packages

- doc/concepts.mld
- doc/dune
- doc/faq.mld
- doc/index.mld
- doc/workflows.mld
This contains a FAQ, a description of the concepts and files, and some workflows.
It is integrated with `dune build @doc` but it is probably up to us to build and host the generated HTML.
> Add documentation for opam-monorepo

- CHANGES.md
- cli/list_cmd.ml
- lib/config.ml
- lib/duniverse.ml
- lib/duniverse.mli
- lib/lockfile.ml
- lib/opam.ml
- lib/opam.mli
- test/lib/test_duniverse.ml
This is a prerequisite PR to the hybrid mode, it sets the `vendor` variable on all packages that we intend to vendor.
I tried running it on `opam-monorepo` and while there is a denylist of packages in `Config.base_packages` it seems to still want to pull packages like `ocaml-config`. I wonder if this is correct or whether we'd need to add more exceptions to it (like when the package version is `"base"` for example).
> Vendor variable in lockfile

- cli/common.ml
- cli/depext.ml
- cli/list_cmd.ml
- cli/lock.ml
- cli/pull.ml
- lib/duniverse.ml
- lib/exec.ml
- lib/git.ml
- lib/lockfile.ml
- lib/opam_solve.ml
- lib/persist.ml
- lib/pin_depends.ml
- lib/project.ml
- lib/pull.ml
- lib/uri_utils.ml
- stdext/result.ml
- stdext/result.mli
We are depending on OCaml 4.08 which supports this syntax already and it makes things a bit easier to read because it is closer to direct style and avoids a little bit of boilerplate. I have used `ppx_let` in the past and it was quite convenient when working with a lot of `result` or `Deferred.t` to just bind them as if they were values.
Only shame about missing `match*` which required binding and matching in some few cases.
> Convert usage of `>>=` into let-syntax

- lib/lockfile.ml
- lib/opam.ml
- lib/opam.mli
This is strictly a refactoring and a small one but it was necessary for the work I am currently doing on reproducible `lock` and thought it might also be of use for #234!
This should make rebasing either of these features easier along with reducing the size of the PRs so it seemed worthwile to extract it to its own PR.
> Move Extra_field out of Lockfile

- README.md
- dune-project
- opam-monorepo.opam
I just published the doc generated from our `.mld` manual to our gh-pages using dune-release. I also added a couple of reference links in the README to make it easier to find.
> Add doc to opam file and README

- CHANGES.md
- lib/opam_solve.ml
We found this issue while pairing.
We should only look at rejected solutions when there is no selected solution. In a scenario where there is 1 selected candidate that builds with dune and all others don't build with dune this would produce a wrong error.
> Only find candidates that can't be built if there is no solution

- stdext/result.ml
Since our minimum version is 4.08 and our module just adds labels to the functions (thus functioning like `ResultLabels` if that existed) it might be somewhat more elegant to just to defer to the built-in implementations.
This makes it a bit clearer that we're not doing anything different from the familiar `map`/`bind`/`map_error` implementations.
> Use `Stdlib.Result` implementations

- cli/lock.ml
This can help understand the baseline for the solver when debugging. It will also prove helpful for users support!
> Add debug log to list locally detected packages

- CHANGES.md
- lib/opam_solve.ml
- test/bin/local-solver-picks-higher-version.t/repo/packages/a/a.0.1/opam
- test/bin/local-solver-picks-higher-version.t/repo/packages/a/a.0.2/opam
- test/bin/local-solver-picks-higher-version.t/repo/packages/base-bigarray/base-bigarray.base/opam
- test/bin/local-solver-picks-higher-version.t/repo/packages/base-threads/base-threads.base/opam
- test/bin/local-solver-picks-higher-version.t/repo/packages/base-unix/base-unix.base/opam
- test/bin/local-solver-picks-higher-version.t/repo/packages/dune/dune.2.9.1/opam
- test/bin/local-solver-picks-higher-version.t/repo/packages/ocaml-base-compiler/ocaml-base-compiler.4.13.1/opam
- test/bin/local-solver-picks-higher-version.t/repo/packages/ocaml-config/ocaml-config.2/opam
- test/bin/local-solver-picks-higher-version.t/repo/packages/ocaml-options-vanilla/ocaml-options-vanilla.1/opam
- test/bin/local-solver-picks-higher-version.t/repo/packages/ocaml/ocaml.4.13.1/opam
- test/bin/local-solver-picks-higher-version.t/repo/repo
- test/bin/local-solver-picks-higher-version.t/run.t
- test/bin/local-solver-picks-higher-version.t/test.opam
It used to prefer older versions over newer ones. This was due to the solver context implementation!
> Fix explicit repo solver

- CHANGES.md
- cli/lock.ml
- lib/opam_solve.ml
- lib/opam_solve.mli
- stdext/option.ml
- stdext/option.mli
- test/bin/invalid-package-version.t/existing.opam
- test/bin/invalid-package-version.t/multiple-constraint.opam
- test/bin/invalid-package-version.t/repo/packages/a/a.0.1/opam
- test/bin/invalid-package-version.t/repo/packages/a/a.1.0/opam
- test/bin/invalid-package-version.t/repo/packages/a/a.1.1/opam
- test/bin/invalid-package-version.t/repo/packages/depends-on-min-a/depends-on-min-a.1/opam
- test/bin/invalid-package-version.t/repo/repo
- test/bin/invalid-package-version.t/run.t
- test/bin/invalid-package-version.t/toonew.opam
I've continued to play around with what info can be retrieved from the map and with a bit of squinting (extracting the version restriction from another rejection case) I was able to test the version check on the packages that we exclude as not building with dune.
If I specify `fmt {>= "1.0.0"}` in my `opam` file I get this error message now:
```
opam-monorepo: [ERROR] Could not find any package that would satisfy the version constrants: fmt
>= 1.0.0
```
It is somewhat involved and hairy so I am not entirely sure whether this is worth it so I'm opening this PR as a draft, more of an RFC to see if we even want to do stuff this way or whether we should patch the 0install solver to expose better information instead.
Closes #215
> Better missing version error

- CHANGES.md
- README.md
- cli/lock.ml
- doc/index.mld
- doc/opam-provided.mld
- lib/duniverse.ml
- lib/duniverse.mli
- lib/lockfile.ml
- lib/lockfile.mli
- lib/opam.ml
- lib/opam.mli
- lib/opam_solve.ml
- lib/opam_solve.mli
- lib/pin_depends.ml
- lib/pp_combinators.ml
- lib/pp_combinators.mli
- lib/source_opam_config.ml
- lib/source_opam_config.mli
- test/bin/opam-provided.t/opam-provided.opam
- test/bin/opam-provided.t/repo/packages/b/b.1/opam
- test/bin/opam-provided.t/repo/packages/depends-on-b/depends-on-b.1/opam
- test/bin/opam-provided.t/repo/repo
- test/bin/opam-provided.t/reverse-transitive.opam
- test/bin/opam-provided.t/run.t
- test/bin/opam-provided.t/transitive.opam
- test/bin/opam-provided.t/vendored.opam
- test/bin/opam-provided.t/warning-list.opam
- test/bin/opam-provided.t/warning.opam
- test/lib/test_duniverse.ml
This is a draft PR on the hybrid mode feature, which makes it possible to actually test things and go somewhere from there.
1. Packages to be installed via `opam` can't be marked as not-installable in the solver because in such case there is no solution. I explored this avenue and it doesn't lead anywhere. At least one part of the solution space eliminated :heavy_check_mark: 
1. There's currently warnings about `opam-provided`, our custom variable. Not great.
1. Variables are false by default so packages marked this way will not be picked up by opam.
1. The detection of the variable is extremely inflexible now. This is just (very necessary) busywork to walk that formula and determine whether the variable is set but needs to be done before release. For testing the concept on examples this …
> Allow marking certain packages as "installed via OPAM"

- CHANGES.md
- cli/pull.ml
- lib/config.ml
- lib/lockfile.ml
- lib/lockfile.mli
- lib/opam.ml
- lib/opam.mli
- stdext/result.ml
- stdext/result.mli
> Check OCaml version of lockfile against the switch version

- CHANGES.md
- lib/opam.ml
- lib/opam.mli
- lib/opam_solve.ml
- test/bin/compiler-beta.t/repo-with-beta-ocaml/packages/ocaml-base-compiler/ocaml-base-compiler.4.14.0~beta1/opam
- test/bin/compiler-beta.t/repo-with-beta-ocaml/packages/ocaml/ocaml.4.14.0/opam
- test/bin/compiler-beta.t/repo-with-beta-ocaml/repo
- test/bin/compiler-beta.t/run.t
- test/bin/compiler-beta.t/test-requires-beta.opam
- test/bin/compiler-beta.t/test.opam
Fixes #265 !
Starting recently, beta versions of the compiler are released as `ocaml-base-compiler` and not `ocaml-variant` anymore. This had the side effect of making our solver pick beta versions if the constraints allowed it.
This fixes this issue but making the solver prefer regular versions over ones flagged with `avoid-version` in their opam metadata.
Such versions can still be selected when no regular version match the requirements.
> Prevent unecessary selection of beta versions

- bin/opam_monorepo.ml
- cli/common.ml
- cli/common.mli
- cli/default.ml
- cli/default.mli
- cli/depext.ml
- cli/depext.mli
- cli/list_cmd.ml
- cli/list_cmd.mli
- cli/lock.ml
- cli/lock.mli
- cli/pull.ml
- cli/pull.mli
- dune-project
- opam-monorepo.opam
- opam-monorepo.opam.locked
- test/bin/invalid-package-version.t/run.t
- test/bin/missing-dune-project.t/run.t
- test/bin/opam-provided.t/run.t
This PR updates the lockfile to use the latest version of cmdliner which introduced a new API and some deprecation warnings.
The upgrade turned some `1` exit codes in the test into `124` which stands for command line options parsing failure and was therefore misleading since those were clearly opam-monorepo errors.
I slightly changed how we turn results into exit codes to fix this but it also fixed other, pre-existing of occurences of false `124`.
> Update to cmdliner.1.1

- lib/pull.ml
The \ syntax does not work in `{|` `|}` enclosed strings so just write the code without it, no big problem.
Closes #277
(`no changelog` label because it is not a user visible change between releases)
> Do not start generated README with backslash

- test/bin/depext.t/a.opam
- test/bin/depext.t/repo/packages/b/b.1/opam
- test/bin/depext.t/repo/repo
- test/bin/depext.t/run.t
We didn't have tests for the depexts, so here's a very basic one that shows that we capture transitive depexts correctly.
Writing a more complicated one is tricky because the packages installed depend on the OS and the state of the OS (whether they are installed or not) and I'd rather not maintain the package names that we use as dummies in the test because this will break on unknown platforms.
> Add a basic test for the depexts

- lib/lockfile.ml
- test/bin/invalid-package-version.t/run.t
- test/bin/local-solver-picks-higher-version.t/run.t
- test/bin/opam-provided.t/run.t
- test/bin/require-cross-compiling-packages.t/run.t
- test/bin/simple-lock.t/run.t
Fixes #257 
Opam has a way to allow undefined variables to be assigned a default value.
Our initial assumption was that it was doing this for all variables but it was wrong. Variables need to be applied the prefix, unary `?` operator.
This PR adds the operator before the `vendor` variable when writing the lockfile. It also expects the variable filter to be written this way when reading it back.
> Improve vendor marking so that it requires no opam configuration

- .ocamlformat
- cli/lock.ml
The let punning syntax is only compatible with 4.13+ so it makes sense to configure the formatter not to use it yet.
> Make the source code compatible with OCaml 4.08 syntax

- CHANGES.md
- lib/config.ml
The warning introduced in #268 had the downside that it only worked when users would use `ocaml-base-compiler`. However, when using variants the compiler is not `ocaml-base-compiler` but `ocaml-variants`, as such the check needs to be relaxed to accept either of these options.
Sidenote: Our `List.mem` from `Stdext` does not support passing in a custom `equal` function, maybe a good idea to add?
Reported by @patricoferris
> Relax ocaml compiler warning to allow ocaml-variants

- doc/faq.mld
Recently Thomas made the official name of opam all lower case, so I'm changing that as I move through all documentation. The only place it will be capitalised moving forward is at the beginning of sentences, so not even in titles.
> minor edits for capitalisation, esp opam

- CHANGES.md
- lib/duniverse.ml
- test/bin/opam-provided.t/run.t
- test/lib/test_duniverse.ml
There is a bug where even despite the package marked as `opam-provided`, opam-monorepo will add it to the Duniverse and thus try to pull and build it.
The logic in the unit test was just plain wrong — an `opam-provided` package should not be part of the Duniverse.
> Filter `opam-provided` from duniverse

- test/bin/require-cross-compiling-packages.t/run.t
Otherwise a warning is printed:
```
warning: here-document at line 1 delimited by end-of-file (wanted `EOF')
```
> Add EOF in test

- .ocamlformat
- dune-project
- opam-monorepo.opam
We discovered during the previous release that some of our vendored dependencies are not compatible with 4.08 anymore.
This PR bumps the lower bound to 4.10 accordingly.
> Fix OCaml lower bound

- CHANGES.md
- cli/lock.ml
- doc/concepts.mld
- doc/index.mld
- doc/lock.mld
- lib/lockfile.ml
- lib/lockfile.mli
- lib/opam_solve.ml
- lib/opam_solve.mli
- test/bin/minimal-update.t/minimal-update.opam
- test/bin/minimal-update.t/repo/packages/a/a.0.1/opam
- test/bin/minimal-update.t/repo/packages/b/b.0.1/opam
- test/bin/minimal-update.t/repo/packages/c/c.0.1/opam
- test/bin/minimal-update.t/repo/repo
- test/bin/minimal-update.t/run.t
This PR adds a `--minimal-update` flag to `lock` which allows for updating the lock file, aiming at minimum changes in the dependencies.
When the flag is passed, the target lockfile (i.e. the one that it will write the generated lock file to) must already exists. It parsed and the list of packages extracted from it. It builds a map `name -> version` that is then passed to the solver. The map is used by the context to promote those version to the top of the preference sorted list of candidates for the package.
This result in different versions only getting picked if no solution exist with the version form the previous lock file. New packages are picked as they normally would and package that are not required anymore are also dropped without issues.
In short the preference order allows us …
> Minimal update of lock file

- CHANGES.md
- cli/lock.ml
- doc/lock.mld
- lib/dune
- lib/serial_shape.ml
- lib/serial_shape.mli
- lib/source_opam_config.ml
- lib/source_opam_config.mli
- test/bin/config-cli-args.t/repo/packages/b/b.1/opam
- test/bin/config-cli-args.t/repo/packages/c/c.1/opam
- test/bin/config-cli-args.t/repo/repo
- test/bin/config-cli-args.t/run.t
- test/bin/opam-provided.t/run.t
- test/lib/test_duniverse_lib.ml
- test/lib/test_serial_shape.ml
- test/lib/test_serial_shape.mli
- test/lib/test_source_opam_config.ml
- test/lib/testable.ml
- test/lib/testable.mli
This PR adds command line arguments to either overwrite or complement `x-opam-monorepo-*` in local opam files.
Each existing field gets a `--<field-name>` option. When this option is passed, its value is used, ignoring local opam files fields.
It also gets a `--add-<field-name>` option to add extra on top of the local opam files fields. It is combined in the same way two fields from different opam files are combined.
It can be useful for experimenting or in certain scenarios where those configuration bits have no natural opam file to be written in.
To be able to do this without writing too much repetitive code I introduced `Serial_shape` which allows to derive both opam and cmdliner parsers and printers from a single value. It simplifies the code of `Source_opam_config` quite a lot.
This …
> Allow passing `x-opam-monorepo-*` solver config fields via the command line.

- CHANGES.md
- cli/lock.ml
- lib/lockfile.ml
- lib/lockfile.mli
- test/bin/cli-args-in-lockfile.t/cli-args-in-lockfile.opam
- test/bin/cli-args-in-lockfile.t/run.t
> Save CLI arguments to the lock file

- CHANGES.md
- cli/lock.ml
OPAM by default filters out packages for which the system on which it is running does not have the depexts. Which is nice in theory but when building a lockfile we want all packages to be available.
The problem here is that some configurations do not have a queryable package list, e.g. when using Docker containers the package list might have been deleted to save on space in the container, thus `available_packages` would be just a subset and missing packages, despite these existing in the OPAM repositories.
This is the reason why on the Tezos CI it needs `apk update` because if the package list is missing it will just silently exclude a lot of the necessary `conf-*` packages. I tested it locally in a Docker container built in the same way as Tezos where I could reproduce the issue and …
> Disable filtering of available packages for availability of their depexts

- CHANGES.md
- lib/lockfile.ml
- test/bin/empty-duniverse.t/empty-duniverse.opam
- test/bin/empty-duniverse.t/run.t
> Fix parsing of lock files with empty duniverses

- CHANGES.md
- cli/depext.ml
> Properly display error message when depext fails

- opam-monorepo.opam.locked
Nothing significant here, not even 5.0.0 compat as the packages required for this (base and ocaml) are still marked as avoid versions for now.
If the need arise we can force their selection by locking again with `--ocaml-version 5.0.0`,
> Update lock file

- doc/lock.mld
change ocaml/opam-repositories to ocaml/opam-repository
> Fix `opam-repositories` typo

- doc/lock.mld
This took a bit of head scratching to understand why this field wasn't working locally ^^"
> Fix use of x-opam-monorepo-global-opam-vars in docs

- lib/config.ml
While attempting to solve a `TODO` I realized it is never used. Then I realized there's more variables that aren't used, so decided to delete these as well. They are probably left over from a time where the tool built OCaml and Dune, but now we assume these are installed.
> Remove unused config variables

- CHANGES.md
- lib/opam.ml
fixes #336 (it now respects the `archive-mirrors` in `~/.opam/config` -- thanks to @kit-ty-kate)
> use cache urls from opam config

- lib/opam.ml
Merging #337 lead to a case where the merging didn't yield a working solution.
This PR fixes it by changing the code to:
- Retrieve the cache urls from the `global_state` as #337 does
- Do not pass cache urls if we're not dealing with an OPAM state
> Fix failed merge of cache URL handling

- CHANGES.md
- lib/duniverse.ml
It is exceedingly annoying to work with pinned packages that are effectively not pinned due to this behavior. Because it was logged at INFO level this log message would not appear in the output without raising the log level.
Related to https://github.com/tarides/opam-monorepo/issues/145 and https://github.com/mirage/mirage/issues/1375
> Warn when using source for different version

- opam-monorepo.opam.locked
Now that `base.v0.15.1` exists, we can update the locked dependencies to "final" releases.
This obsoletes https://github.com/tarides/opam-monorepo/pull/325
> Update the lock file to OCaml 5

- cli/common.ml
- cli/depext.ml
- cli/dune
- cli/import.ml
- cli/list_cmd.ml
- cli/lock.ml
- cli/pull.ml
- dune-project
- lib/dune
- lib/pp_combinators.mli
- opam-monorepo.opam
- test/lib/test_duniverse.ml
- test/lib/test_source_opam_config.ml
This is useful for releases where we're supposed to bump the dune-lang version. But opam-monorepo is currently not compatible with newer versions of dune so this PR attempts to fix things.
> Dune 3.5 update

- CHANGES.md
- lib/git.ml
- test/bin/pinning.t/opam-monorepo-test-other/opam-monorepo-test-other.opam
- test/bin/pinning.t/run.t
- test/bin/pinning.t/this/this.opam
When using a pinned dependency the refs might not have a prefix (e.g. `HEAD` is a plain ref) thus they wouldn't have been found when attempting to resolve the refs.
Closes #326
> Allow resolving unprefixed refs

- lib/opam.ml
- lib/opam.mli
Signed-off-by: Stephen Sherratt <stephen@sherra.tt>
In https://github.com/tarides/opam-monorepo/pull/355 I wanted to add a new field to `Package_summary.t`:
```ocaml
build : OpamTypes.command list
```
...but found it would be non-trivial to implement `equal` or `pp` for the `OpamTypes.command` type. This would only be necessary to update the `Package_summary.equal` and `Package_summary.pp` functions, but I found that they aren't called anywhere in this project.
> Remove some dead code

- CHANGES.md
- lib/config.ml
- lib/duniverse.ml
- lib/lockfile.ml
- lib/opam.ml
- lib/opam.mli
- lib/opam_solve.ml
- test/lib/test_duniverse.ml
This changes the logic from hardcoding the compiler "base packages" to instead read the OPAM flags to check whether the package in question is a compiler in which case it will be considered a base package.
It also adds code to check for packages whether they are `conf` packages, which could be used to check for virtual packages.
Inspired by #327, this would allow `dkml-base-compiler` to be considered a base package and not accidentally vendor it. However it doesn't yet allow using the DKML compiler, because the name of the `ocaml` conf package is still hardcoded with no way to override it (yet).
> Read package flags from OPAM metadata

- CHANGES.md
- lib/opam.ml
- lib/opam.mli
- test/bin/invalid-package-version.t/repo/packages/a/a.0.1/opam
- test/bin/invalid-package-version.t/repo/packages/a/a.1.0/opam
- test/bin/invalid-package-version.t/repo/packages/a/a.1.1/opam
- test/bin/local-solver-picks-higher-version.t/repo/packages/a/a.0.2/opam
- test/bin/local-solver-picks-higher-version.t/run.t
- test/bin/minimal-update.t/repo/packages/a/a.0.1/opam
- test/bin/minimal-update.t/repo/packages/b/b.0.1/opam
- test/bin/minimal-update.t/repo/packages/c/c.0.1/opam
- test/bin/no-build-command.t/repo/packages/depend-with-dune/depend-with-dune.0.1/opam
- test/bin/no-build-command.t/repo/packages/depend-without-dune/depend-without-dune.0.1/opam
- test/bin/no-build-command.t/repo/packages/with-dune/with-dune.0.1/opam
- test/bin/no-build-command.t/repo/packages/without-dune/without-dune.0.1/opam
- test/bin/no-build-command.t/repo/repo
- test/bin/no-build-command.t/run.t
- test/bin/no-build-command.t/test-depend-with-dune.opam
- test/bin/no-build-command.t/test-depend-without-dune.opam
- test/bin/opam-provided.t/repo/packages/depends-on-b/depends-on-b.1/opam
- test/bin/require-cross-compiling-packages.t/mirage-opam-overlays/packages/b/b.0.1+dune+mirage/opam
- test/bin/require-cross-compiling-packages.t/opam-overlays/packages/b/b.0.1+dune/opam
- test/bin/require-cross-compiling-packages.t/opam-repository/packages/b/b.0.1/opam
- test/bin/require-cross-compiling-packages.t/run.t
- test/bin/simple-lock.t/repo/packages/b/b.1/opam
- test/bin/simple-lock.t/repo/packages/c/c.1/opam
- test/lib/test_duniverse.ml
If a package has no build commands, chances are that it's a metapackage which exists just so that its dependencies can be installed.
Signed-off-by: Stephen Sherratt <stephen@sherra.tt>
> Allow packages with no build commands

- test/bin/config-cli-args.t/run.t
- test/bin/dune
- test/bin/explicit-repo.t/run.t
- test/bin/invalid-package-version.t/run.t
- test/bin/lockfile-version.t/run.t
- test/bin/minimal-update.t/run.t
Some commands used in tests use features not available on macos:
- `sed -i ...` requires a file extension to be passed as an argument, and the original file is preserved as a copy with the given extension appended
- `grep -P ...` is not implemented
I updated the tests to use perl instead as its behaviour will be consistent across different unixes.
Also, when using homebrew as a package manager, opam incorrectly reports non-existent packages as available, presumably because brew provides no fast way to query for the existence of non-installed packages. This was causing a depext test to fail on macos.
Signed-off-by: Stephen Sherratt <stephen@sherra.tt>
> Make tests compatible with macos

- CHANGES.md
- lib/duniverse.ml
- lib/opam.ml
- test/bin/missing-dev-repo.t/missing-dev-repo.opam
- test/bin/missing-dev-repo.t/repo/packages/no-dev-repo/no-dev-repo.1/opam
- test/bin/missing-dev-repo.t/repo/repo
- test/bin/missing-dev-repo.t/run.t
Adds a warning as suggested by @kit-ty-kate.
Fixes #341
> Add warning when `dev-repo` is missing

- doc/opam-provided.mld
Please check to see all the "opam"s are formatted to differentiate between opam, the package manager, and `opam` the command. There were some in there I wasn't sure about. I'll leave comments where.
> minor edits for formatting, clarity, consistency, and capitalisation

- CHANGES.md
- lib/duniverse.ml
- lib/uri_utils.ml
- lib/uri_utils.mli
- test/lib/test_uri_utils.ml
This PR tries to normalize the `dev-repo` URLs somewhat. @TheLortex reported in #118 that the `.git` is differing between the repos so this PR tries to normalize the URLs:
1. Always have `.git` in the repo path
2. Always use `git+https` as scheme
3. Always strip fragments (No more `#main`)
This is just a workaround since there is no way to make sure the URLs are equivalent without visiting them (especially the `.git` addition is a bit dodgy), but it should at least cover some common cases and in the worst case the canonicalization gives up and returns the input, thus equivalent to what was there before.
Also turns out there was a `Uri_utils.has_git_extension` which I assume is somewhat related to the issue at hand, but it was unused so I removed it. 
Closes #118
> Normalize Github URLs before comparing

- CHANGES.md
- lib/dune_file.ml
- lib/dune_file.mli
- lib/pull.ml
Previously it only processed files that have been affected by renames which is not enough if the files refer to vendored libraries that have been renamed.
Fix for undetected issue in #367 that was discovered during testing with RWO.
Fixes #370.
> Process all `dune` files in the project when applying renames

- CHANGES.md
- lib/dune_file.ml
- lib/opam.ml
Currently `opam-monorepo` is skipping over files with the Tuareg stanza when renaming, but not when updating the references. Oddly enough Sexplib parses these files successfully, but outputting them breaks down so we need to make sure to skip files with the Tuareg stanza even when updating the references.
> Do not rewrite `dune` files in ML format when updating references

- lib/dune_file.ml
- lib/dune_file.mli
- lib/pull.ml
As I am testing the renaming facility I came across some bugs:
I think this doesn't need a changelog entry since it is not a change from the latest released version, more a set of follow-up bugfixes for #367 that have been detected in production projects.
> Distinguish private vs public names when vendoring names

- CHANGES.md
- lib/dev_repo.ml
- lib/dev_repo.mli
- lib/duniverse.ml
- test/bin/error-on-directory-conflict.t/repo/packages/bar/bar.0.1.0/opam
- test/bin/error-on-directory-conflict.t/repo/packages/foo-branch/foo-branch.0.1.0/opam
- test/bin/error-on-directory-conflict.t/repo/packages/foo/foo.0.1.0/opam
- test/bin/error-on-directory-conflict.t/run.t
- test/bin/error-on-directory-conflict.t/x.opam
The duniverse directory of a package is implied by its dev-repo. It's possible for different dev-repos to map to the same directory. Prior to this change, one lucky package would be downloaded to the expected place and the others would be silently ignored. More precisely, each package would be downloaded and placed in the duniverse dir implied by their dev-repo, but first any existing duniverse dir of the same name would be removed.
After this change, the same situation results in an error when running `opam monorepo lock`.
> Error when multiple dev-repos collide on dir

- CHANGES.md
- lib/opam.ml
- lib/opam.mli
- test/lib/test_duniverse.ml
Reported by @gridbugs that `xml-light.2.4` is missing `build` but is not a virtual package due to having `install`.
This simplifies the previous detection a little bit, since the build commands (and by extension the install commands) are never used, so just recording their presence or absence should be enough.
> Mark packages as virtual when they have neither `build` nor `install`

- CHANGES.md
- cli/lock.ml
- test/bin/no-build-command.t/run.t
When trying to generate a lockfile on a package which has dependencies which don't use dune as their build system, the diagnostic message generated by opam-0install is of little use. This change removes the opam-0install diagnostic message from the output of `opam monorepo lock` in the case where it fails due to dependencies not building with dune.
Additionally this rewords the error message to highlight the salient information. In particular the list of non-dune packages is printed as a bulleted list rather than a comma-separated list inside the error message (it often takes me a minute to find the list of packages in the old error message).
> Simplify error message when deps don't build with dune

- cli/lock.ml
#381 introduced an additional check, but unfortunately `String.starts_with` was only added in OCaml 4.13. This PR uses an equivalent function from Base that is available in OCaml 4.10.
> Use `is_prefix` which is available in OCaml 4.10

- test/bin/empty-duniverse.t/run.t
Apparently `grep` now warns about this, causing a test failure:
```
diff --git a/_build/.sandbox/89b1e78a9e8830d72e7bb32e1bc4651d/default/test/bin/empty-duniverse.t/run.t b/_build/.sandbox/89b1e78a9e8830d72e7bb32e1bc4651d/default/test/bin/empty-duniverse.t/run.t.corrected
index 3380874c..1601055d 100644
--- a/_build/.sandbox/89b1e78a9e8830d72e7bb32e1bc4651d/default/test/bin/empty-duniverse.t/run.t
+++ b/_build/.sandbox/89b1e78a9e8830d72e7bb32e1bc4651d/default/test/bin/empty-duniverse.t/run.t.corrected
@@ -16,6 +16,7 @@ We should be able to successfully lock:
And the lock file should not contain anything to vendor:
$ opam show --just-file -fdepends ./empty-duniverse.opam.locked | grep "\?vendor"
+  grep: warning: stray \ before ?
[1]
Finally, we should be able to pull this lock file, the …
```
> Remove backslash escape from `grep` call

- CHANGES.md
- lib/dev_repo.ml
- lib/dev_repo.mli
- lib/duniverse.ml
- lib/opam_solve.ml
- test/lib/test_duniverse.ml
- test/lib/test_solve.ml
Convert the constraint "if X and Y are from the same repository" into a conflict relationship in the opam metadata between `X` and all the version of `Y` which do not have the same exact version as `X`.
This allow to remove the adhoc post-processing of opam solution which was going very wrong in lots of case. Hopefully, the results will now be much closer to what you would expect `opam` to produce.
> Remove custom deduplication of packages and use opam solver instead

- CHANGES.md
- lib/duniverse.ml
- lib/duniverse.mli
- lib/opam.ml
- lib/opam.mli
- lib/opam_solve.ml
- lib/opam_solve.mli
- test/lib/dune
- test/lib/test_duniverse.ml
- test/lib/test_duniverse_lib.ml
- test/lib/test_solve.ml
This allows to pin a single package for multi-repository. In that case Opam-monorepo will always choose the pinned repository, so adding conflicts is just confusing the solver.
> Ignore pinned packages when building dev-repo conflicts

- CHANGES.md
- cli/common.ml
- cli/list_cmd.ml
- cli/lock.ml
- cli/pull.ml
- dune-project
- lib/dev_repo.ml
- lib/dune
- lib/dune_file.ml
- lib/duniverse.ml
- lib/git.ml
- lib/lockfile.ml
- lib/opam.ml
- lib/pull.ml
- lib/serial_shape.ml
- lib/source_opam_config.ml
- lib/uri_utils.ml
- opam-monorepo.opam
- opam-monorepo.opam.locked
- test/lib/test_source_opam_config.ml
This drops the dependency on base. In #410 (CC @gm0stache) it is reported that opam-monorepo fails to install on Mac OS on ARM. The error message suggests the compilation fails in base. This rewrites all calls to base to use the standard library. Certainly, there are things that could be factored out to functions, but it's mostly straight forward.
@gm0stache: can you try see if this works for you?
> Drop dependency on base

- CHANGES.md
- lib/opam_solve.ml
- test/lib/test_solve.ml
When a repository contains both virtual and non-virtual packages, avoid the conflict that is generated because the virtual package has no `src` while the non-virtual package has one, so their hash list appear superficially incompatible.
The issue came up with `ocaml-unikraft*` packages: `ocaml-unikraft` is a virtual package to depend on one of the possible packages (according to the target architecture), but the same `dev-repo` also contains the actual non-virtual packages `ocaml-unikraft` is there to depend upon. Before this patch, `opam-monorepo` created a conflict between them.
> Avoid generating conflicts with virtual packages from the same repository
