tarides/opam-monorepo

- lib/dune_cmd.ml
- lib/opam_cmd.ml
- lib/types.ml
Small refactorings ahead of the merge of the opam and lock commands and files to keep the PRs size reasonable!
> Refactor Opam_cmd

- lib/dune_cmd.ml
- lib/opam_cmd.ml
Even if a duniverse fork is needed, the user might be able to fetch it manually so it doesn't really make sense to stop and not downloading anything.
> Warn instead of failing when a package is invalid.

- doc/spec.md
This is a WIP. I'm opening the PR so we can discuss those the spec!
cc @samoht @avsm 
Not much as happened since it was posted on slack but I'll keep you updated whenever I make significant changes.
> Draft a new spec for duniverse

- cli/init.ml
- cli/pull.ml
- cli/styled_pp.ml
- cli/styled_pp.mli
- lib/dune_cmd.ml
These are a few tiny improvements to the code of the `duniverse pull` command ahead of the `vendored_dirs` stanza support in duniverse!
> Small improvement to Duniverse_cli.Pull

- duniverse.opam
We should probably wait until 1.11 is released to merge that but it should be any day now!
> Unpin dune

- dune-project
- duniverse.opam
- lib/dune
> Drop ezjsonm dependency

- lib/duniverse.ml
- test/test_duniverse.ml
Nothing too bad but the test weren't testing much because of that!
> Fix Duniverse.Deps.Source.equal

- dune-project
The opam file was updated instead of the `dune-project`!
> Fix dune-project according to latest opam file changes

- cli/update.ml
Depends on #67 and #67, I'll undraft once they're merged!
This adds arguments to the `duniverse update` command so that you can update the tracked commit for a subset of the duniverse! This can be pretty convenient!
> Allow to `duniverse update` specific repositories

- cli/init.ml
- lib/config.ml
- lib/opam_cmd.ml
- lib/pins.ml
- lib/repo.ml
- lib/repo.mli
I found this as I was working on the new lock files and extracted those couple commits so it doesn't have to wait on the broader feature being merged!
> Fix a bug where pin wouldn't work properly with --repo

- cli/pull.ml
- lib/opam.ml
- lib/opam.mli
- lib/pull.ml
- lib/pull.mli
- stdext/result.ml
- stdext/result.mli
Depends on #131 
This PR cleans up the Pull module which was a bit messy and uses OpamParallel to achieve parallel pulling according to the opam configuration!
> Clean up pull's code and re-enable parallel pulling

- dune-project
- opam-monorepo.opam
This is required as we vendor the dune repo which uses dune language version 2.7
> Require dune 2.7 or higher

- CHANGES.md
- lib/duniverse.ml
- lib/lockfile.ml
- lib/opam.ml
- lib/opam.mli
- lib/pp_combinators.ml
- lib/pp_combinators.mli
- opam-monorepo.opam.locked
- test/test_duniverse.ml
> Include transitive depexts in the lockfile

- CHANGES.md
- cli/lock.ml
Just a minor fix in the error message.
> Remove mention of duniverse, use opam monorepo instead.

- cli/lock.ml
These can have version numbers.
> Document LOCAL_PACKAGE syntax for lock

- lib/lockfile.ml
- lib/opam.ml
- lib/opam.mli
Similarly to what I did in #239, I'm extracting this work that seem be mutually beneficial to #234 and my current work on reproducible lock.
> Move OpamVariable.FullPos utilities to Opam

- lib/lockfile.ml
- lib/opam.ml
- lib/opam.mli
This allows me to use this code for the explicit repo feature!
> Factor opam value parsing out of Lockfile

- dune-project
- opam-monorepo.opam
The project seems to build fine on my machine with dune 3. I had some test failures that seemed unrelated (incompatible grep CLI used in cram tests)
> Relax constraint on dune to support dune 3

- test/bin/compiler-beta.t/run.t
- test/bin/depext.t/run.t
- test/bin/invalid-package-version.t/run.t
- test/bin/lockfile-version.t/run.t
- test/bin/opam-provided.t/run.t
- test/bin/require-cross-compiling-packages.t/run.t
This speeds up the tests quite a bit and prevents it from trying to write anything which will help when sandboxed!
> Use opam show --just-file in cram tests

- CONTRIBUTING.md
- doc/concepts.mld
> minor line edits for CONTRIBUTING.md

- CONTRIBUTING.md
This updates the instruction for setting up the dev environment according to the changes in opam-monorepo.0.3.
CC @christinerose: If you have spare time for some proofreading! Since you recently polished this bit of documentation, let's try not to mess it up from the get-go!
> Update CONTRIBUTING.md according to opam-monorepo.0.3 upgrade

- README.md
Fixed just a few capitalisations and other formatting. 
> minor line editing for ReadMe

- doc/concepts.mld
> minor change for consistency in syntax

- opam-monorepo.opam
- opam-monorepo.opam.locked
- opam-monorepo.opam.template
There has been a release of opam-0install incorporating the changes we needed so we can unpin it now!
> Unpin opam-0install and update lock file

- opam-monorepo.opam.locked
We don't use any particular options so no extra field for us.
> Update lock file

- README.md
Thanks to @n-osborne for the report
> Update documentation to new URL now that the repo moved

- doc/workflows.mld
I changed any duniverse to `duniverse`, as that's how it was formatted in the previous document. Would you prefer `duniverse`, duniverse, or Duniverse? I'll update the style guide and make changes when the formatting choice is official.
> line editing for consistency, etc.

- bin/opam_monorepo.ml
Trying to attack the amount of issues and this is a very low hanging fruit. Might as well.
Closes #280
> Use a more maintained repo as an example for usage

- CHANGES.md
- cli/common.ml
- cli/common.mli
- cli/pull.ml
- lib/pull.ml
- lib/pull.mli
- test/bin/preserve-symlinks.t/preserve-symlinks.opam
- test/bin/preserve-symlinks.t/repo/packages/symlinked-dep/symlinked-dep.1.0/opam
- test/bin/preserve-symlinks.t/repo/repo
- test/bin/preserve-symlinks.t/run.t
> Preserve symlinks in `duniverse/` if requested

- CHANGES.md
- cli/depext.ml
- dune-project
- lib/config.ml
- lib/opam.ml
- lib/opam_solve.ml
- opam-monorepo.opam
- opam-monorepo.opam.locked
Dear developpers,
This PR was needed to compile some of my unikernels with opam 2.3.
Best.
> Allow opam-2.3 series
